const topics = {
  History: [
    "Ancient Indian History",
    "Modern Indian History",
    "The Renaissance",
    "World War II",
    "The American Revolution",
    "Indus Valley Civilization",
    "Mughal Empire",
    "British Rule in India",
    "Indian Independence Movement",
    "Post-Independence India",
  ],
  Biology: [
    "Cell Biology",
    "Genetics",
    "Human Physiology",
    "Ecology",
    "Evolution",
    "Plant Anatomy and Physiology",
    "Human Reproductive System",
    "Health and Diseases",
    "Biotechnology",
    "Microbiology",
    "Food Production",
    "Chloroplast",
    "	Mitochondria",
    " Vacuoles",
    "Endoplasmic reticulum",
    "Golgi apparatus",
    "Nucleus",
    "Chromosomes Basic structure",
    "Structure and functions of animal and plant tissues",
    "Four types of tissues in animals",
    "Meristematic and Permanent tissues in plants",
    "Animal kingdom",
    "Plant kingdom",
  ],
  Physics: [
    "Classical Mechanics",
    "Quantum Physics",
    "Electromagnetism",
    "Relativity",
    "Thermodynamics",
    "Motion and Measurement of Distances",
    "Light and Sound",
    "Electricity and Magnetism",
    "Work and Energy",
    "Simple Machines",
    "Motion, Force, and Work",
    "Thrust and Pressure",
    "Archimedes Principle",
    "Buoyancy",
  ],
  Chemistry: [
    "Organic Chemistry",
    "Inorganic Chemistry",
    "Physical Chemistry",
    "Biochemistry",
    "Analytical Chemistry",
    "Matter in Our Surroundings",
    "Atoms and Molecules",
    "Acids, Bases, and Salts",
    "Periodic Table of Elements",
    "Chemical Reactions",
    "Elements",
    "Compounds",
    "Mixtures",
    "Heterogeneous and homogenous mixtures",
    "Colloids",
    "Suspensions",
  ],
  Geography: [
    "Physical Geography",
    "Human Geography",
    "Climate and Weather",
    "Natural Resources",
    "Population and Settlement",
    "Geographical Tools and Techniques",
    "Maps and Globes",
    "Indian Geography",
    "World Geography",
    "Environmental Issues",
    "indian map",
  ],
  IndianPolity: [
    "Constitution of India",
    "Fundamental Rights and Duties",
    "Union and State Government",
    "Elections in India",
    "Political Parties in India",
    "Local Government",
    "Constitutional Amendments",
    "Judiciary System",
    "Political System",
    "Citizenship",
  ],
  Economics: [
    "Basic Economic Concepts",
    "Types of Economic Systems",
    "Supply and Demand",
    "Money and Banking",
    "Inflation",
    "Public Finance",
    "International Trade",
    "Economic Development",
    "Poverty and Unemployment",
    "Economic Planning",
  ],
};

module.exports = topics;
