const topics = {
  History: [
    "Ancient Indian History",
    "Modern Indian History",
    "The Renaissance",
    "World War II",
    "The American Revolution",
    "Indus Valley Civilization",
    "Mughal Empire",
    "British Rule in India",
    "Indian Independence Movement",
    "Post-Independence India",
  ],
  Biology: [
    "Cell Biology",
    "Genetics",
    "Human Physiology",
    "Ecology",
    "Evolution",
    "Plant Anatomy and Physiology",
    "Human Reproductive System",
    "Health and Diseases",
    "Biotechnology",
    "Microbiology",
  ],
  Physics: [
    "Classical Mechanics",
    "Quantum Physics",
    "Electromagnetism",
    "Relativity",
    "Thermodynamics",
    "Motion and Measurement of Distances",
    "Light and Sound",
    "Electricity and Magnetism",
    "Work and Energy",
    "Simple Machines",
  ],
  Chemistry: [
    "Organic Chemistry",
    "Inorganic Chemistry",
    "Physical Chemistry",
    "Biochemistry",
    "Analytical Chemistry",
    "Matter in Our Surroundings",
    "Atoms and Molecules",
    "Acids, Bases, and Salts",
    "Periodic Table of Elements",
    "Chemical Reactions",
  ],
  Geography: [
    "Physical Geography",
    "Human Geography",
    "Climate and Weather",
    "Natural Resources",
    "Population and Settlement",
    "Geographical Tools and Techniques",
    "Maps and Globes",
    "Indian Geography",
    "World Geography",
    "Environmental Issues",
  ],
  IndianPolity: [
    "Constitution of India",
    "Fundamental Rights and Duties",
    "Union and State Government",
    "Elections in India",
    "Political Parties in India",
    "Local Government",
    "Constitutional Amendments",
    "Judiciary System",
    "Political System",
    "Citizenship",
  ],
  Economics: [
    "Basic Economic Concepts",
    "Types of Economic Systems",
    "Supply and Demand",
    "Money and Banking",
    "Inflation",
    "Public Finance",
    "International Trade",
    "Economic Development",
    "Poverty and Unemployment",
    "Economic Planning",
  ],
};

module.exports = topics;
